# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: language_id.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'language_id.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11language_id.proto\x12\x0fzemberek.langid\"b\n\x11LanguageIdRequest\x12\r\n\x05input\x18\x01 \x01(\t\x12\x16\n\x0emaxSampleCount\x18\x02 \x01(\x05\x12\x0f\n\x07trGroup\x18\x03 \x01(\x08\x12\x15\n\rincludeScores\x18\x04 \x01(\x08\"Q\n\x12LanguageIdResponse\x12\x0e\n\x06langId\x18\x01 \x01(\t\x12+\n\x08idResult\x18\x02 \x03(\x0b\x32\x19.zemberek.langid.IdResult\"%\n\x08IdResult\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\x32\xbd\x01\n\x11LanguageIdService\x12Q\n\x06\x44\x65tect\x12\".zemberek.langid.LanguageIdRequest\x1a#.zemberek.langid.LanguageIdResponse\x12U\n\nDetectFast\x12\".zemberek.langid.LanguageIdRequest\x1a#.zemberek.langid.LanguageIdResponseB\x12\n\x0ezemberek.protoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'language_id_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016zemberek.protoP\001'
  _globals['_LANGUAGEIDREQUEST']._serialized_start=38
  _globals['_LANGUAGEIDREQUEST']._serialized_end=136
  _globals['_LANGUAGEIDRESPONSE']._serialized_start=138
  _globals['_LANGUAGEIDRESPONSE']._serialized_end=219
  _globals['_IDRESULT']._serialized_start=221
  _globals['_IDRESULT']._serialized_end=258
  _globals['_LANGUAGEIDSERVICE']._serialized_start=261
  _globals['_LANGUAGEIDSERVICE']._serialized_end=450
# @@protoc_insertion_point(module_scope)
