# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import zemberek_grpc.preprocess_pb2 as preprocess__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in preprocess_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PreprocessingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Tokenize = channel.unary_unary(
                '/zemberek.preprocessor.PreprocessingService/Tokenize',
                request_serializer=preprocess__pb2.TokenizationRequest.SerializeToString,
                response_deserializer=preprocess__pb2.TokenizationResponse.FromString,
                _registered_method=True)
        self.ExtractSentences = channel.unary_unary(
                '/zemberek.preprocessor.PreprocessingService/ExtractSentences',
                request_serializer=preprocess__pb2.SentenceExtractionRequest.SerializeToString,
                response_deserializer=preprocess__pb2.SentenceExtractionResponse.FromString,
                _registered_method=True)


class PreprocessingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Tokenize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractSentences(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PreprocessingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Tokenize': grpc.unary_unary_rpc_method_handler(
                    servicer.Tokenize,
                    request_deserializer=preprocess__pb2.TokenizationRequest.FromString,
                    response_serializer=preprocess__pb2.TokenizationResponse.SerializeToString,
            ),
            'ExtractSentences': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractSentences,
                    request_deserializer=preprocess__pb2.SentenceExtractionRequest.FromString,
                    response_serializer=preprocess__pb2.SentenceExtractionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zemberek.preprocessor.PreprocessingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('zemberek.preprocessor.PreprocessingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PreprocessingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Tokenize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zemberek.preprocessor.PreprocessingService/Tokenize',
            preprocess__pb2.TokenizationRequest.SerializeToString,
            preprocess__pb2.TokenizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractSentences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zemberek.preprocessor.PreprocessingService/ExtractSentences',
            preprocess__pb2.SentenceExtractionRequest.SerializeToString,
            preprocess__pb2.SentenceExtractionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
