# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: preprocess.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'preprocess.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10preprocess.proto\x12\x15zemberek.preprocessor\"`\n\x13TokenizationRequest\x12\r\n\x05input\x18\x01 \x01(\t\x12\x1e\n\x16includeTokenBoundaries\x18\x02 \x01(\x08\x12\x1a\n\x12ignoreDoubleQuotes\x18\x03 \x01(\x08\"E\n\nTokenProto\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05start\x18\x03 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x04 \x01(\x05\"I\n\x14TokenizationResponse\x12\x31\n\x06tokens\x18\x01 \x03(\x0b\x32!.zemberek.preprocessor.TokenProto\"O\n\x19SentenceExtractionRequest\x12\x10\n\x08\x64ocument\x18\x01 \x01(\t\x12 \n\x18\x64oNotSplitInDoubleQuotes\x18\x02 \x01(\x08\"/\n\x1aSentenceExtractionResponse\x12\x11\n\tsentences\x18\x01 \x03(\t2\xf4\x01\n\x14PreprocessingService\x12\x63\n\x08Tokenize\x12*.zemberek.preprocessor.TokenizationRequest\x1a+.zemberek.preprocessor.TokenizationResponse\x12w\n\x10\x45xtractSentences\x12\x30.zemberek.preprocessor.SentenceExtractionRequest\x1a\x31.zemberek.preprocessor.SentenceExtractionResponseB\x12\n\x0ezemberek.protoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'preprocess_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016zemberek.protoP\001'
  _globals['_TOKENIZATIONREQUEST']._serialized_start=43
  _globals['_TOKENIZATIONREQUEST']._serialized_end=139
  _globals['_TOKENPROTO']._serialized_start=141
  _globals['_TOKENPROTO']._serialized_end=210
  _globals['_TOKENIZATIONRESPONSE']._serialized_start=212
  _globals['_TOKENIZATIONRESPONSE']._serialized_end=285
  _globals['_SENTENCEEXTRACTIONREQUEST']._serialized_start=287
  _globals['_SENTENCEEXTRACTIONREQUEST']._serialized_end=366
  _globals['_SENTENCEEXTRACTIONRESPONSE']._serialized_start=368
  _globals['_SENTENCEEXTRACTIONRESPONSE']._serialized_end=415
  _globals['_PREPROCESSINGSERVICE']._serialized_start=418
  _globals['_PREPROCESSINGSERVICE']._serialized_end=662
# @@protoc_insertion_point(module_scope)
