# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import zemberek_grpc.spellcheck_pb2 as spellcheck__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in spellcheck_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SpellCheckServiceStub(object):
    """SpellCheck Service Definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/zemberek.proto.SpellCheckService/Check',
                request_serializer=spellcheck__pb2.SpellCheckRequest.SerializeToString,
                response_deserializer=spellcheck__pb2.SpellCheckResponse.FromString,
                _registered_method=True)
        self.Suggest = channel.unary_unary(
                '/zemberek.proto.SpellCheckService/Suggest',
                request_serializer=spellcheck__pb2.SuggestionRequest.SerializeToString,
                response_deserializer=spellcheck__pb2.SuggestionResponse.FromString,
                _registered_method=True)
        self.CheckBatch = channel.unary_unary(
                '/zemberek.proto.SpellCheckService/CheckBatch',
                request_serializer=spellcheck__pb2.BatchSpellCheckRequest.SerializeToString,
                response_deserializer=spellcheck__pb2.BatchSpellCheckResponse.FromString,
                _registered_method=True)


class SpellCheckServiceServicer(object):
    """SpellCheck Service Definition
    """

    def Check(self, request, context):
        """Check if a word is spelled correctly
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Suggest(self, request, context):
        """Get suggestions for a word
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckBatch(self, request, context):
        """Check multiple words at once
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpellCheckServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=spellcheck__pb2.SpellCheckRequest.FromString,
                    response_serializer=spellcheck__pb2.SpellCheckResponse.SerializeToString,
            ),
            'Suggest': grpc.unary_unary_rpc_method_handler(
                    servicer.Suggest,
                    request_deserializer=spellcheck__pb2.SuggestionRequest.FromString,
                    response_serializer=spellcheck__pb2.SuggestionResponse.SerializeToString,
            ),
            'CheckBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckBatch,
                    request_deserializer=spellcheck__pb2.BatchSpellCheckRequest.FromString,
                    response_serializer=spellcheck__pb2.BatchSpellCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zemberek.proto.SpellCheckService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('zemberek.proto.SpellCheckService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpellCheckService(object):
    """SpellCheck Service Definition
    """

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zemberek.proto.SpellCheckService/Check',
            spellcheck__pb2.SpellCheckRequest.SerializeToString,
            spellcheck__pb2.SpellCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Suggest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zemberek.proto.SpellCheckService/Suggest',
            spellcheck__pb2.SuggestionRequest.SerializeToString,
            spellcheck__pb2.SuggestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zemberek.proto.SpellCheckService/CheckBatch',
            spellcheck__pb2.BatchSpellCheckRequest.SerializeToString,
            spellcheck__pb2.BatchSpellCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
