# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spellcheck.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'spellcheck.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10spellcheck.proto\x12\x0ezemberek.proto\"!\n\x11SpellCheckRequest\x12\x0c\n\x04word\x18\x01 \x01(\t\"7\n\x12SpellCheckResponse\x12\x12\n\nis_correct\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\":\n\x11SuggestionRequest\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x17\n\x0fmax_suggestions\x18\x02 \x01(\x05\"8\n\x12SuggestionResponse\x12\x13\n\x0bsuggestions\x18\x01 \x03(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\'\n\x16\x42\x61tchSpellCheckRequest\x12\r\n\x05words\x18\x01 \x03(\t\"\xbc\x01\n\x17\x42\x61tchSpellCheckResponse\x12H\n\x07results\x18\x01 \x03(\x0b\x32\x37.zemberek.proto.BatchSpellCheckResponse.WordCheckResult\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x1aH\n\x0fWordCheckResult\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x12\n\nis_correct\x18\x02 \x01(\x08\x12\x13\n\x0bsuggestions\x18\x03 \x03(\t2\x94\x02\n\x11SpellCheckService\x12N\n\x05\x43heck\x12!.zemberek.proto.SpellCheckRequest\x1a\".zemberek.proto.SpellCheckResponse\x12P\n\x07Suggest\x12!.zemberek.proto.SuggestionRequest\x1a\".zemberek.proto.SuggestionResponse\x12]\n\nCheckBatch\x12&.zemberek.proto.BatchSpellCheckRequest\x1a\'.zemberek.proto.BatchSpellCheckResponseB\x12\n\x0ezemberek.protoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spellcheck_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016zemberek.protoP\001'
  _globals['_SPELLCHECKREQUEST']._serialized_start=36
  _globals['_SPELLCHECKREQUEST']._serialized_end=69
  _globals['_SPELLCHECKRESPONSE']._serialized_start=71
  _globals['_SPELLCHECKRESPONSE']._serialized_end=126
  _globals['_SUGGESTIONREQUEST']._serialized_start=128
  _globals['_SUGGESTIONREQUEST']._serialized_end=186
  _globals['_SUGGESTIONRESPONSE']._serialized_start=188
  _globals['_SUGGESTIONRESPONSE']._serialized_end=244
  _globals['_BATCHSPELLCHECKREQUEST']._serialized_start=246
  _globals['_BATCHSPELLCHECKREQUEST']._serialized_end=285
  _globals['_BATCHSPELLCHECKRESPONSE']._serialized_start=288
  _globals['_BATCHSPELLCHECKRESPONSE']._serialized_end=476
  _globals['_BATCHSPELLCHECKRESPONSE_WORDCHECKRESULT']._serialized_start=404
  _globals['_BATCHSPELLCHECKRESPONSE_WORDCHECKRESULT']._serialized_end=476
  _globals['_SPELLCHECKSERVICE']._serialized_start=479
  _globals['_SPELLCHECKSERVICE']._serialized_end=755
# @@protoc_insertion_point(module_scope)
